# Generated by Django 5.2.7 on 2025-12-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
